name = "marketing-site.nko"
image = "bcoe/nko-marketing-site:1.0.0_11_a0a37dbc"

[scale]
  containers = 1
  ram = "> 50 Mi < 200 Mi"
  cpu = "> 1% < 20%"

[env]
  ETCD = "etcd.data:2379"
  SERVICE_NAME = "marketing-site"
  NODE_ENV = "production"

[ports]
  http = "8082"
