name = "marketing-site.nko"
image = "bcoe/nko-marketing-site:badges-server_1.0.0_0_6ac9429b"

[scale]
  containers = 1
  ram = "> 50 Mi < 200 Mi"
  cpu = "> 1% < 20%"

[env]
  ETCD = "etcd.data:2379"
  SERVICE_NAME = "marketing-site"
  # [env.shared-config]

[ports]
  http = "8082"
